excluded:
  - Pods
  - "Stranger-Chat/Services/Realm/RealmManager.swift"
  - "Stranger-Chat/Injection/*.swift"
line_length: 150
disabled_rules:
  - nesting
  - multiple_closures_with_trailing_closure
  - trailing_whitespace
