osx_image: xcode10.1
language: objective-c
rvm:
 - 1.29.4
podfile: Podfile
before_install:
 - bundle install
 - bundle exec pod repo update
 - bundle exec pod install
after_success:
 - bash <(curl -s https://codecov.io/bash) -J 'Stranger-Chat'